# Generated by Django 5.2 on 2025-06-24 11:49

import catalogue.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', catalogue.managers.UserManager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='Signé',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='artwork',
            name='is_signed',
            field=models.BooleanField(choices=[('True', 'Yes'), ('False', 'No')], default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='artworks',
            field=models.ManyToManyField(to='catalogue.artwork'),
        ),
        migrations.AlterField(
            model_name='contextualreference',
            name='reference_type',
            field=models.CharField(choices=[('EXHIBITION_CATALOGUE', 'Exhibition Catalogue'), ('ALBUM', 'Album'), ('BOOK', 'Book'), ('MAGAZINE', 'Magazine'), ('ARTICLE', 'Article'), ('NEWSPAPER', 'Newspaper'), ('WEBSITE', 'Website'), ('SOCIAL_MEDIA', 'Social Media'), ('OTHER_MEDIA', 'Other Media'), ('DISK_COVER', 'Disk Cover'), ('MOVIE_POSTER', 'Movie Poster'), ('POSTCARD', 'Postcard'), ('POSTER', 'Poster'), ('ADVERTISING', 'Advertising'), ('PACKAGING', 'Packaging'), ('OTHER', 'Other')], default='OTHER', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='artwork',
        ),
    ]
