# Generated by Django 5.2.3 on 2025-06-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_user_managers_alter_wishlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
