# Generated by Django 5.2.3 on 2025-06-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_artist_pseudonym'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='images',
            field=models.ImageField(blank=True, upload_to='media/artworks/'),
        ),
    ]
