TECHNIQUES = [
    "Peinture à l'huile",
    "Aquarelle",
    "Photographie argentique",
    "Art numérique",
    "Fusain",
    "Crayon",
    "Impression 3D",
    "Acrylique",
    "Gouache",
    "Pastel",
    "Tempera",
    "Encaustique",
    "Encre",
    "Fresque",
    "Collage",
    "Assemblage",
    "Chiaroscuro",
    "Divisionnisme",
    "Cire perdue",
    "Trompe-l'œil",
    "Impasto",
    "Sgraffito",
    "Glazing",
    "Hatching",
    "Stippling",
    "Blending",
    "Scumbling",
    "Dry brushing",
    "Wash",
    "Underpainting",
    "Alla prima",
    "Plein air",
    "Mixed media",
    "Spray painting",
    "Airbrushing",
    "Screen printing",
    "Lithographie",
    "Eau-forte",
    "Woodcut",
    "Linocut",
]

SUPPORTS = [
    "Toile",
    "Papier glacé",
    "Marbre",
    "Papier",
    "Panneau de bois",
    "Masonite",
    "Métal",
    "Ivoire",
    "Vélin",
    "Soie",
    "Clayboard",
    "Verre",
    "Plâtre",
    "Cuir",
    "Tissu",
    "Carton",
    "MDF",
    "Panneau durci",
    "Plexiglas",
    "Tuiles céramiques",
    "Pierre",
]

ART_TYPES = [
    "Peinture",
    "Photographie",
    "Dessin",
    "Sculpture",
    "Gravure",
    "Art d'installation",
    "Art de performance",
    "Art numérique",
    "Art vidéo",
    "Céramique",
    "Textiles",
    "Art du verre",
    "Métallerie",
    "Joaillerie",
    "Architecture",
    "Design graphique",
    "Illustration",
    "Calligraphie",
    "Bande dessinée",
    "Art de la bande dessinée",
]